version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=e-commerce
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db: