version: "3"
services:
  app:
    container_name: app:0.1
    image: dockerfile
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo:0.1
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'